# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160729_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='/imgs'),
        ),
    ]
