# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160729_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='/imgs'),
        ),
    ]
